### ISSUE TITLE
React native is not a hybrid app

### ISSUE THREAD

**Issue by Schabaani** [yazdan/career-path#14]
With [React Native](https://facebook.github.io/react-native/), you don't build a "mobile web app", an "HTML5 app", or a "hybrid app". You build a real mobile app that's indistinguishable from an app built using Objective-C or Java.

**Comment by mpourismaiel** [comment]
@Schabaani What changes do you propose? The subject includes both React Native and Xaramin which I think is actually hybrid. If possible please provide a PR or if not let me know what changes are required.

**Comment by Schabaani** [comment]
پی آر فرستادم. 
خروجی ری اکت نیتیو اپ هیبریدی یا وب اپ نیست؛ واقعا یک اپ واقعی است. کدها در انتها تبدیل به آبجکتیو سی یا جاوا می شوند.  در مورد زامارین رو نمی دونم دقیقا چجوری هست.

**Comment by yazdan** [comment]
سلام دستتون درد نکنه
