### ISSUE TITLE
Add a resources document

### ISSUE THREAD

**Issue by mpourismaiel** [yazdan/career-path#7]
علاوه بر لیست مهارت‌هایی که نیازه به نظرم منابع مرتبطشون هم در دسترس بذارین خیلی کاربردی‌تر میشه.

**Comment by yazdan** [comment]
بله منم موافقم باید بتونیم توی این جا به این سوالات جواب دیم که 
* چه شغلی؟
* چه مهارتی؟
*  اون مهارت‌ها از چه طریقی بدست بیاریم؟
حالا اگه به نظر شما باید به سوال دیگه‌ای هم جواب بدیم بگید

**Comment by mpourismaiel** [comment]
یه پول ریکوئست میدم تا چند دقیقه دیگه که شغل‌ها و لینک‌های آموزشی و لیست‌های awesome مربوطش رو اضافه میکنه تو یه فایل مخصوص اون موضوع. اگه مشکلی داشت روی همون پول‌ریکوئست صحبت کنیم.

**Comment by yazdan** [comment]
دست شما درد نکنه
